name: Build Windows
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Dependencies
      run: |
        choco install wget
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/example/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        archives: 'qtbase qtsvg'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==3.1.*'
        py7zrversion: '==0.20.*'
        extra: '--external 7z'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.5'

    - name: Get Boost
      uses: actions/checkout@v4
      with:
        repository: 'boostorg/boost'
        path: 'boost'
        ref: 'boost-1.81.0'
        submodules: 'recursive'
        
    - name: Compile Boost
      run: |
        cd boost*
        mkdir build64
        cd build64
        cmake .. -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS=OFF -DBUILD_CLAR=OFF
        cmake --build . --config Release
    
    - name: Get fritzing-parts
      uses: actions/checkout@v4
      with:
        repository: 'fritzing/fritzing-parts'
        path: 'fritzing-parts'
    
    - name: Get quazip
      uses: actions/checkout@v4
      with:
        repository: 'stachenov/quazip'
        path: 'quazip-qt6'

    
