name: Build Windows
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Dependencies
      run: |
        choco install wget
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/example/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        archives: 'qtbase qtsvg'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'true'
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        set-env: 'true'
        tools-only: 'false'
        aqtversion: '==3.1.*'
        py7zrversion: '==0.20.*'
        extra: '--external 7z'

                
    - name: Get Boost
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.7z
    
    - name: Get fritzing-parts
      uses: actions/checkout@v4
      with:
        repository: 'fritzing/fritzing-parts'
        path: 'fritzing-parts'
    
    - name: Get quazip
      uses: actions/checkout@v4
      with:
        repository: 'stachenov/quazip'
        path: 'quazip-qt6'

    
